### ISSUE TITLE
 Notes encryption can be bypassed during the running 

### ISSUE THREAD

**Issue by bigshans** [Daniele-rolli/Beaver-Notes#116]
### Summary

Notes encryption can be bypassed during the running.

### Details

Although exported and imported data is encrypted, encrypted notes while the application is running are unencrypted. So hackers can easily get the encrypted notes.

For example, the code from HomeNoteCard.vue:

```javascript
          const hashHex = hashArray
            .map((byte) => byte.toString(16).padStart(2, '0'))
            .join('');
          if (hashHex === sharedKey) {
              // ...
          }
```

No password is needed after I changed it:

```javascript
          let hashHex = hashArray
            .map((byte) => byte.toString(16).padStart(2, '0'))
            .join('');
          hashHex = sharedKey;
          if (hashHex === sharedKey) {
            // ...
          }
```

Of course, we can also get data from devtools. That's easier.

This is a very serious bug that needs to be fixed. Password protection is effectively useless during running. In my opinion, only the encrypted text needs to be saved. If the key is wrong, an error will be thrown during decryption. You needn't store sharedKey.

**Comment by Daniele-rolli** [comment]
I believe we can review how password handling works. However, it's important to note that locked notes are meant to lock the notes, not encrypt them. So, currently, the content isn't encrypted, as far as I am aware. We could encrypt it, but I don't think it would integrate well with the current storing system. Rewriting the system would be necessary to properly handle writing and reading encrypted notes

**Comment by Daniele-rolli** [comment]
A little follow-up: I just realized what you meant by getting data from dev tools, and I see how big the issue is now. Still, I have no idea where to store the key.

**Comment by bigshans** [comment]
> A little follow-up: I just realized what you meant by getting data from dev tools, and I see how big the issue is now. Still, I have no idea where to store the key.

This is frontend encryption, and the frontend should not store any keys.

**Comment by Daniele-rolli** [comment]
I'll look into solving it. I think we could just save the key like we do with notes, making them inaccessible from dev-tools or anywhere else except for the app.

**Comment by bigshans** [comment]
> I'll look into solving it. I think we could just save the key like we do with notes, making them inaccessible from dev-tools or anywhere else except for the app.

That can only rely on user input or additional key files.

**Comment by Daniele-rolli** [comment]
Ok, my idea is to store it like we do with notes, so have Pinia keep track of everything and use Electron's way of storing data. Furthermore, we could also use a salted hash key, so a real hacker would have to go a long way before even trying to unlock a note.

**Comment by bigshans** [comment]
> Ok, my idea is to store it like we do with notes, so have Pinia keep track of everything and use Electron's way of storing data. Furthermore, we could also use a salted hash key, so a real hacker would have to go a long way before even trying to unlock a note.

What is the logic of decryption?

**Comment by Daniele-rolli** [comment]
What do you mean? Our issue is that the notes can be unlocked by using the key's hash, right? Because it is easily accessible. We just move that somewhere where it cannot be found and salt it, so that even if someone found the key, it wouldn't straight up work. The rest stays as is. Does it sound right to you, or is there something I should change?

**Comment by bigshans** [comment]
> What do you mean? Our issue is that the notes can be unlocked by using the key's hash, right? Because it is easily accessible. We just move that somewhere where it cannot be found and salt it, so that even if someone found the key, it wouldn't straight up work. The rest stays as is. Does it sound right to you, or is there something I should change?

I actually didn't know the password and bypassed the unlock since I could modify the memory in devtools.

**Comment by bigshans** [comment]
And your content isn't encrypted, so there's no need for hackers to deal with passwords.

**Comment by Daniele-rolli** [comment]
Well, I don't think there is really a need to, as the note itself isn't stored as a plain text file and therefore isn't accessible through the filesystem.

**Comment by Daniele-rolli** [comment]
Hey, could you check the development branch and see if what I've pushed is enough to fix our encryption issue?

**Comment by bigshans** [comment]
> Hey, could you check the development branch and see if what I've pushed is enough to fix our encryption issue?

I need to sleep. I'm a bit busy tomorrow and may have to confirm later.

**Comment by Daniele-rolli** [comment]
Sure, no problem. It's not that urgent anyway.

**Comment by bigshans** [comment]
1. Can't be unlocked even the password is correct.
2. Can be bypass.

https://github.com/Daniele-rolli/Beaver-Notes/assets/26884666/c5ee4a75-275c-4be9-9ffd-a6820cc31d9e

If the content is not encrypted, there is no need to care about the password at all. At present, it is best not to save passwords and other private information in notes, because it is easy to be hacked.

**Comment by bigshans** [comment]
To be honest, it's just a warning that "lock" doesn't fully protect its contents.

**Comment by Daniele-rolli** [comment]
Okay, I guess it's time to rewrite the locking mechanism. My idea is to encrypt the note content using AES-128 like so 

```javascript
    async lockNote(id, password) {
      if (!password) {
        console.error('No password provided.');
        return; // Exit the function if no password is provided
      }

      // Perform encryption only if password is provided
      try {
        const encryptedContent = AES.encrypt(
          JSON.stringify(this.data[id].content),
          password
        ).toString();

        this.data[id].content = encryptedContent;
        this.data[id].isLocked = true;
        this.isLocked[id] = true;
        // Save encrypted note data to storage
        await storage.set(`notes.${id}`, this.data[id]);
        // Update lock status in storage
        this.lockStatus[id] = 'locked';
        this.isLocked[id] = true;
        await Promise.all([
          storage.set('lockStatus', this.lockStatus),
          storage.set('isLocked', this.isLocked),
        ]);
        console.log(`Note (ID: ${id}) is locked`);
      } catch (error) {
        console.error('Error locking note:', error);
        throw error;
      }
    },
```

This logic only encrypts the content, as other information is pretty much useless and should be enough to fix our issue along with a salted password hash.

**Comment by bigshans** [comment]
> Okay, I guess it's time to rewrite the locking mechanism. My idea is to encrypt the note content using AES-128 like so 
> 
> ```javascript
>     async lockNote(id, password) {
>       if (!password) {
>         console.error('No password provided.');
>         return; // Exit the function if no password is provided
>       }
> 
>       // Perform encryption only if password is provided
>       try {
>         const encryptedContent = AES.encrypt(
>           JSON.stringify(this.data[id].content),
>           password
>         ).toString();
> 
>         this.data[id].content = encryptedContent;
>         this.data[id].isLocked = true;
>         this.isLocked[id] = true;
>         // Save encrypted note data to storage
>         await storage.set(`notes.${id}`, this.data[id]);
>         // Update lock status in storage
>         this.lockStatus[id] = 'locked';
>         this.isLocked[id] = true;
>         await Promise.all([
>           storage.set('lockStatus', this.lockStatus),
>           storage.set('isLocked', this.isLocked),
>         ]);
>         console.log(`Note (ID: ${id}) is locked`);
>       } catch (error) {
>         console.error('Error locking note:', error);
>         throw error;
>       }
>     },
> ```
> 
> This logic only encrypts the content, as other information is pretty much useless and should be enough to fix our issue along with a salted password hash.

Yes, this is what I mean.

**Comment by Daniele-rolli** [comment]
I've just pushed the commit that should fix the locking issue once and for all. Check it out when you can and let me know if everything seems to work correctly.

**Comment by bigshans** [comment]
The algorithm of encrypting and decrypting might have some bug which I can't unlock the note.

**Comment by bigshans** [comment]
Maybe the way of using salt has some problems.

**Comment by Daniele-rolli** [comment]
Personally, I haven't encountered any issues during testing. Could you provide some details on what's not working for you?

**Comment by Daniele-rolli** [comment]
I forgot to tell you that this method is not 1:1 compatible with the old locking and unlocking logic. So, if you are trying to unlock a note that was locked in a previous version, it might error out as it checks the password against both the stored hash and the content of the note.

**Comment by bigshans** [comment]
> I forgot to tell you that this method is not 1:1 compatible with the old locking and unlocking logic. So, if you are trying to unlock a note that was locked in a previous version, it might error out as it checks the password against both the stored hash and the content of the note.

No, I cleaned all hashes in storage and used `123` as my password.

**Comment by Daniele-rolli** [comment]
Uhm I should look into this for now I've adapted the unlock logic to recognize the old way we locked notes so we can still unlock them.

**Comment by Daniele-rolli** [comment]
By the way, try exporting your notes and checking if the ‘isLocked’ flag is set to true even on notes you locked before this fix was pushed.

**Comment by bigshans** [comment]
I delete all data to refresh the app then lock the new note. But I can't unlock it once I lock it.

Here is my new exported data.

https://pastebin.com/Ft7udvjq

The password is `123`.

**Comment by Daniele-rolli** [comment]
Something isn't working for sure; it says isLocked=true, but the content is there in plain sight, which is not supposed to happen.

**Comment by Daniele-rolli** [comment]
While I figure out the issue, try out [96f40c7](https://github.com/Daniele-rolli/Beaver-Notes/commit/96f40c73d436ce0c3c69d3b973b2bd0282dc9104).

**Comment by bigshans** [comment]
I extracted the encryption and decryption logic and did a test, and you can try it out.
By the way, I still can't unlock.

https://pastebin.com/wSUsDrup

**Comment by Daniele-rolli** [comment]
You were actually right; the issue is in the passwd.json file, and it seems like the logic is unable to check if the password is correct. So, I’ll rewrite it and let you know.

**Comment by Daniele-rolli** [comment]
The commit I've just pushed should fix our issue once and for all.

**Comment by bigshans** [comment]
> The commit I've just pushed should fix our issue once and for all.

Yes, now I can lock and unlock the note normally.
Well, can you add some tips about locking?  Because it's very difficult for users to retrieve their data once they forget their password. Features such as changing the password, removing the lock on the note, and removing the password should be necessary. They are very useful for me.

**Comment by Daniele-rolli** [comment]
We could let the user reset the password if they remember their old one. The new unlock logic is already able to distinguish between notes that have been encrypted before this bug was discovered and notes encrypted after, so we are in the clear as far as retro compatibility. However, how would you handle resetting the password if the user has completely forgotten it?

**Comment by bigshans** [comment]
Tips only to tell users that once the password data is forgotten, it cannot be retrieved.

**Comment by bigshans** [comment]
Wait a minute, I found a new bug. If I relock the note with a new password, the note can not be unlocked again.

**Comment by Daniele-rolli** [comment]
Fixed, now it checks if the password you're trying to use is the one you set up or just another one.

**Comment by Daniele-rolli** [comment]
I've finally implemented a way to reset the password, along with a tip: Warning, if you forget your password, you'll lose access to your locked notes, and setting a new password will require knowing the old one.

**Comment by Daniele-rolli** [comment]
I guess everything checks out, so we just need @eag75 and @mee_ to update their translations by adding the following to theirs, and then we’re all set for version 2.8.0

```

"card": {
    "Passwdcorrect": "Password is incorrect.",
    "warning": "Warning, if you forget your password, you'll lose access to your locked notes, and setting a new password will require knowing the old one."
  },

```

and 

```
"settings": {
    "resetPasswordTitle": "Enter Current Password",
    "next": "Next",
    "enterNewPassword": "Enter new password",
    "resetPassword": "Reset Password",
    "newpassword": "Insert new password",
    "utilities": "Utilities",
    "security": "Password & Security",
    "warning": "Warning, if you forget your password, you'll lose access to your locked notes, and setting a new password will require knowing the old one.",
    "wrongCurrentPassword": "Wrong password, please try again",
    "passwordResetError": "Something went wrong while resetting your password",
    "passwordResetSuccess": "The password has been reset successfully"
  },
```
